npmPublishAccess: public

npmPublishRegistry: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
enableInlineHunks: true
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-compat.cjs
    spec: '@yarnpkg/plugin-compat'
